USE [DeepSeaKingdom]
GO
CREATE VIEW [WE].[V_CheckKey__ExternalDB.Mark_DB]
--WITH ENCRYPTION
AS
SELECT kcu.table_name as TABLE_NAME, kcu.column_name as PRIMARY_KEY_COLUMN, tc.CONSTRAINT_TYPE
FROM [ExternalDB].Mark_DB.INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc JOIN [ExternalDB].Mark_DB.INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME 
		AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
--ORDER BY kcu.TABLE_NAME, kcu.ORDINAL_POSITION;