USE [DeepSeaKingdom]
GO
CREATE VIEW [WE].[V_CheckAccess__OracleDB.CSPRD]
--WITH ENCRYPTION
AS
SELECT DISTINCT * FROM OPENQUERY ([OPRO], 'SELECT * FROM Person_TAB_PRIVS WHERE GRANTEE = ''SYSHYU''')